jest.mock('react-native', () => ({
  Platform: { OS: 'web' },
}));

import { inviteTokenFromInstallReferrer } from '../installReferrerInvite';

describe('Google Play install-referrer invitation handoff', () => {
  test('extracts and normalizes the invite token generated by the landing page', () => {
    expect(inviteTokenFromInstallReferrer('invite_token=inv-ab12cd34')).toBe('INV-AB12CD34');
  });

  test('accepts encoded referrers with additional attribution fields', () => {
    expect(
      inviteTokenFromInstallReferrer(
        'utm_source=email&invite_token=INV-ABC123&campaign=family',
      ),
    ).toBe('INV-ABC123');
  });

  test('rejects organic and malformed referrers', () => {
    expect(inviteTokenFromInstallReferrer('utm_source=google-play&utm_medium=organic')).toBeNull();
    expect(inviteTokenFromInstallReferrer('invite_token=not-an-invite')).toBeNull();
  });
});