const mockGetInstallReferrerInfo = jest.fn();
const mockSetPendingInvite = jest.fn();

jest.mock('react-native', () => ({
  Platform: { OS: 'android' },
}));

jest.mock('react-native-play-install-referrer', () => ({
  PlayInstallReferrer: {
    getInstallReferrerInfo: (...args: any[]) => mockGetInstallReferrerInfo(...args),
  },
}));

jest.mock('../pendingInvite', () => ({
  setPendingInvite: (...args: any[]) => mockSetPendingInvite(...args),
}));

import {
  captureInstallReferrerInvite,
  INSTALL_REFERRER_STARTUP_TIMEOUT_MS,
  inviteTokenFromInstallReferrer,
} from '../installReferrerInvite';

describe('Google Play install-referrer invitation handoff', () => {
  beforeEach(() => {
    jest.useRealTimers();
    mockGetInstallReferrerInfo.mockReset();
    mockSetPendingInvite.mockReset();
  });

  test('extracts and normalizes the invite token generated by the landing page', () => {
    expect(inviteTokenFromInstallReferrer('invite_token=inv-ab12cd34')).toBe('INV-AB12CD34');
  });

  test('accepts encoded referrers with additional attribution fields', () => {
    expect(
      inviteTokenFromInstallReferrer(
        'utm_source=email&invite_token=INV-ABC123&campaign=family',
      ),
    ).toBe('INV-ABC123');
  });

  test('rejects organic and malformed referrers', () => {
    expect(inviteTokenFromInstallReferrer('utm_source=google-play&utm_medium=organic')).toBeNull();
    expect(inviteTokenFromInstallReferrer('invite_token=not-an-invite')).toBeNull();
  });

  test('does not block startup forever when Play never invokes its callback', async () => {
    jest.useFakeTimers();
    mockGetInstallReferrerInfo.mockImplementation(() => {});

    const capture = captureInstallReferrerInvite();
    await jest.advanceTimersByTimeAsync(INSTALL_REFERRER_STARTUP_TIMEOUT_MS);

    await expect(capture).resolves.toBeNull();
  });

  test('does not block startup when persisting a captured invite fails', async () => {
    mockSetPendingInvite.mockRejectedValueOnce(new Error('storage unavailable'));
    mockGetInstallReferrerInfo.mockImplementation((callback) => {
      callback({ installReferrer: 'invite_token=INV-ABC123' }, null);
    });

    await expect(captureInstallReferrerInvite()).resolves.toBeNull();
  });

  test('does not block startup when the native referrer call throws synchronously', async () => {
    mockGetInstallReferrerInfo.mockImplementation(() => {
      throw new Error('native bridge unavailable');
    });

    await expect(captureInstallReferrerInvite()).resolves.toBeNull();
  });

  test('handles only the first callback when the native module responds twice', async () => {
    mockSetPendingInvite.mockResolvedValue(undefined);
    mockGetInstallReferrerInfo.mockImplementation((callback) => {
      void callback({ installReferrer: 'invite_token=INV-FIRST1' }, null);
      void callback({ installReferrer: 'invite_token=INV-SECOND2' }, null);
    });

    await expect(captureInstallReferrerInvite()).resolves.toBe('INV-FIRST1');
    expect(mockSetPendingInvite).toHaveBeenCalledTimes(1);
    expect(mockSetPendingInvite).toHaveBeenCalledWith('INV-FIRST1');
  });

  test('still persists a valid invite when the callback arrives after startup continues', async () => {
    jest.useFakeTimers();
    let referrerCallback: ((info: any, error: any) => Promise<void>) | null = null;
    mockGetInstallReferrerInfo.mockImplementation((callback) => {
      referrerCallback = callback;
    });
    mockSetPendingInvite.mockResolvedValueOnce(undefined);

    const capture = captureInstallReferrerInvite();
    await jest.advanceTimersByTimeAsync(INSTALL_REFERRER_STARTUP_TIMEOUT_MS);
    await expect(capture).resolves.toBeNull();

    expect(referrerCallback).not.toBeNull();
    await referrerCallback!({ installReferrer: 'invite_token=INV-LATE123' }, null);
    expect(mockSetPendingInvite).toHaveBeenCalledWith('INV-LATE123');
  });
});